image: registry.gitlab.com/app4business/docker-images/meteor:6078dd1204091ec11611661f9311a8c3b64a435e

stages:
  - build

variables:
  TOOL_NODE_FLAGS: --max-old-space-size=4096

cache:
  paths:
  - "node_modules"
  - ".meteor"
  - ".npm"
  - ".node-gyp"
  - "build/RocketChat/Rocket.Chat/node_modules"
  - "build/RocketChat/Rocket.Chat/.meteor/local"
  - "build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/.npm"
  - "build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/.app/node_modules"
  - "build/RocketChat/Rocket.Chat/packages/rocketchat-livechat/.app/.meteor/local"


build:
  stage: build
  artifacts:
    name: build
    paths:
    - "$HOME/build"
  script:
    - echo "$HOME"
    - &install if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi
    - export PATH="$HOME/.meteor:$PATH"
    - meteor npm install
    - meteor build --server-only $HOME/build
    - rm -rf build/RocketChat/Rocket.Chat/.meteor/local/log
    - rm -rf build/RocketChat/Rocket.Chat/.meteor/local/run
    - rm -rf build/RocketChat/Rocket.Chat/.meteor/local/db

